version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    expose:
      - '5432'
    networks:
        - broadcom
    volumes:
      - ./postgres_volume:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_DEFAULT_PORT}:80
    networks:
        - broadcom
  mysql:
    image: mysql
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3309:3306
    networks:
        - broadcom
    volumes:
      - ./mysql_volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
        - 8080:80
    environment:
        MYSQL_ROOT_PASSWOR: '${DB_PASSWORD}'
        PMA_HOST: mysql
        PMA_PORT: 3306
    depends_on:
        - mysql
    networks:
        - broadcom
networks:
    broadcom:
        driver: bridge































